#!/usr/bin/env python3
"""Generate and run additional k-point IBZ-reduction regression cases.

The published `validation/` tree covers cubic Si and Al only.  This companion
extends the same kind of check to the 12 Materials-Project structures pinned in
`regtest_inputs.tar.gz`, across four Monkhorst-Pack/MacDonald meshes:

    4x4x4 shifted, 4x4x4 Gamma-centred, 6x6x6 shifted, 6x6x6 Gamma-centred

Each case is generated from `structures.json` (cell, atomic coordinates, KIND
definitions and SCF settings transcribed from the original `regtest_*.inp`
inputs).  For every system and mesh a symmetry-reduced run (`SYMMETRY .TRUE.`)
is written and, with `--full`, a full-grid companion (`SYMMETRY .FALSE.`).

Usage
-----
    # write the input files only (no CP2K binary required)
    python3 run_additional.py --generate-only

    # run everything with a pinned build and check count + energy
    python3 run_additional.py --binary /path/to/cp2k.ssmp --source /path/to/cp2k \
        --threads 1 --rerun

    # restrict to a subset
    python3 run_additional.py --generate-only \
        --systems CoF2_rutile,PI2_tric --meshes 4x4x4-shifted,6x6x6-gamma

Exit status is non-zero if any generated case fails to reproduce its expected
irreducible k-point count or (where a converged reference exists) its pinned
energy.  `full` runs, when requested, are only checked for consistency with the
matching reduced run; they have no independent reference.
"""
import argparse
import json
import os
from pathlib import Path
import re
import subprocess
import time

ROOT = Path(__file__).resolve().parent
COMMIT = "dd94896b48d429648fb3640799c9d198ff8de1e3"


def kind_block(kind):
    lines = [f"    &KIND {kind['name']}"]
    if "element" in kind:
        lines.append(f"      ELEMENT {kind['element']}")
    if "magnetization" in kind:
        lines.append(f"      MAGNETIZATION {kind['magnetization']}")
    lines.append(f"      BASIS_SET {kind['basis_set']}")
    lines.append(f"      POTENTIAL {kind['potential']}")
    lines.append("    &END KIND")
    return "\n".join(lines)


def scf_block(scf):
    lines = ["    &SCF", f"      SCF_GUESS {scf.get('scf_guess', 'ATOMIC')}",
             f"      EPS_SCF {scf['eps_scf']:.1E}", f"      MAX_SCF {scf['max_scf']}",
             f"      ADDED_MOS {scf.get('added_mos', 10)}"]
    mixing = scf.get("mixing")
    if mixing:
        lines += ["      &MIXING", f"        METHOD {mixing['method']}",
                  f"        ALPHA {mixing['alpha']}", f"        NBUFFER {mixing['nbuffer']}",
                  "      &END MIXING"]
    smearing = scf.get("smearing")
    if smearing:
        lines += ["      &SMEAR", f"        METHOD {smearing['method']}",
                  f"        ELECTRONIC_TEMPERATURE [K] {smearing['temperature_k']}",
                  "      &END SMEAR"]
    lines += ["      &PRINT", "        &RESTART OFF", "        &END RESTART",
              "      &END PRINT", "    &END SCF"]
    return "\n".join(lines)


def input_text(system, mesh, symmetry, backend=None, eps_symmetry=1.0e-5):
    lat = system["lattice"]
    cell = (f"      ABC  {lat['a']:.10f}  {lat['b']:.10f}  {lat['c']:.10f}\n"
            f"      ALPHA_BETA_GAMMA  {lat['alpha']:.6f}  {lat['beta']:.6f}  {lat['gamma']:.6f}")
    coords = "\n".join(
        f"      {name}  {x:.10f}  {y:.10f}  {z:.10f}"
        for name, x, y, z in system["coords"])
    kinds = "\n".join(kind_block(k) for k in system["kinds"])
    mgrid = {"cutoff": 600, "rel_cutoff": 60} | system.get("mgrid", {})
    gamma = "\n      GAMMA_CENTERED .TRUE." if mesh["gamma_centered"] else ""
    backend_line = f"\n      SYMMETRY_BACKEND {backend}" if backend else ""
    if symmetry:
        sym_lines = f"      SYMMETRY .TRUE.\n      EPS_SYMMETRY {eps_symmetry:.1E}" + backend_line
    else:
        sym_lines = "      SYMMETRY .FALSE.\n      FULL_GRID .TRUE."
    return f"""! CP2K k-point IBZ regression — generated by run_additional.py
! Structure:   {system['note']}
! Source:      regtest_inputs (Materials Project)
! Mesh:        {mesh['name']}
! Symmetry reduction: {'ON' if symmetry else 'OFF (full grid)'}
!
&GLOBAL
  PROJECT {system['label']}
  RUN_TYPE ENERGY
  PRINT_LEVEL MEDIUM
&END GLOBAL

&FORCE_EVAL
  METHOD QS

  &DFT
    LSD .TRUE.
    BASIS_SET_FILE_NAME  BASIS_MOLOPT
    POTENTIAL_FILE_NAME  GTH_POTENTIALS

    &MGRID
      CUTOFF {mgrid['cutoff']}
      REL_CUTOFF {mgrid['rel_cutoff']}
    &END MGRID

    &QS
      EPS_DEFAULT 1.0E-12
    &END QS

{scf_block(system['scf'])}

    &XC
      &XC_FUNCTIONAL PBE
      &END XC_FUNCTIONAL
    &END XC

    &KPOINTS
      SCHEME {mesh['scheme']}
      WAVEFUNCTIONS COMPLEX
{sym_lines}{gamma}
    &END KPOINTS

  &END DFT

  &SUBSYS
    &CELL
{cell}
      PERIODIC XYZ
    &END CELL

    &COORD
      SCALED .TRUE.
{coords}
    &END COORD

{kinds}
  &END SUBSYS

&END FORCE_EVAL
"""


def parse_output(text):
    def last(pattern):
        matches = re.findall(pattern, text, re.M)
        return float(matches[-1]) if matches else None

    return {
        "converged": "SCF run converged" in text and "SCF run NOT converged" not in text,
        "energy_hartree": last(r"ENERGY\| Total FORCE_EVAL.*?([-+0-9.Ee]+)\s*$"),
        "nk": last(r"BRILLOUIN\|\s+List of Kpoints.*?\]\s+(\d+)"),
    }


def build_cases(doc, systems, meshes, full):
    cases = []
    for system in doc["systems"]:
        if systems and system["label"] not in systems:
            continue
        for mesh in doc["meshes"]:
            if meshes and mesh["name"] not in meshes:
                continue
            cases.append({"system": system, "mesh": mesh, "symmetry": True})
            if full:
                cases.append({"system": system, "mesh": mesh, "symmetry": False})
    return cases


def case_name(system, mesh, symmetry):
    return f"{system['label']}-{mesh['name']}-{'sym' if symmetry else 'full'}"


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--structures", type=Path, default=ROOT / "structures.json")
    parser.add_argument("--output-dir", type=Path, default=ROOT / "inputs")
    parser.add_argument("--generate-only", action="store_true",
                        help="write inputs but do not invoke CP2K")
    parser.add_argument("--binary", type=Path, help="CP2K executable")
    parser.add_argument("--source", type=Path, help="pinned CP2K checkout (provides data/)")
    parser.add_argument("--datadir", type=Path, help="override CP2K_DATA_DIR")
    parser.add_argument("--threads", type=int, default=1)
    parser.add_argument("--rerun", action="store_true",
                        help="re-run cases even if a complete output already exists")
    parser.add_argument("--full", action="store_true",
                        help="also generate full-grid companions (SYMMETRY .FALSE.)")
    parser.add_argument("--systems", default="",
                        help="comma-separated labels, default all")
    parser.add_argument("--meshes", default="",
                        help="comma-separated mesh names, default all")
    parser.add_argument("--backend", choices=["K290", "SPGLIB"],
                        help="optional SYMMETRY_BACKEND for reduced runs")
    parser.add_argument("--eps-symmetry", type=float, default=1.0E-5,
                        help="KPOINTS%%EPS_SYMMETRY for reduced runs")
    parser.add_argument("--check-energies", action="store_true",
                        help="treat the pinned reference energies as hard checks; by default the "
                             "absolute energy is recorded but only checked for the pinned commit")
    parser.add_argument("--ref-tol", type=float, default=1.0E-5,
                        help="tolerance on pinned reference energy [Ha] (with --check-energies)")
    parser.add_argument("--eq-tol", type=float, default=1.0E-8,
                        help="tolerance between reduced and full-grid runs [Ha]")
    parser.add_argument("--skip-version-check", action="store_true")
    parser.add_argument("--reuse-only", action="store_true",
                        help="reparse existing outputs and rewrite results without invoking CP2K")
    parser.add_argument("--strict-scf", action="store_true",
                        help="fail if any run does not reach SCF convergence; by default the "
                             "known-hard CoF2/BaFe2As2 cases may abort after printing the k-point list")
    args = parser.parse_args()
    if args.threads < 1:
        parser.error("--threads must be positive")

    doc = json.loads(args.structures.read_text())
    systems = {s.strip() for s in args.systems.split(",") if s.strip()}
    meshes = {s.strip() for s in args.meshes.split(",") if s.strip()}
    unknown = systems - {s["label"] for s in doc["systems"]}
    unknown |= meshes - {m["name"] for m in doc["meshes"]}
    if unknown:
        parser.error(f"unknown system/mesh: {', '.join(sorted(unknown))}")

    cases = build_cases(doc, systems, meshes, args.full)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for case in cases:
        name = case_name(case["system"], case["mesh"], case["symmetry"])
        directory = args.output_dir / name
        directory.mkdir(parents=True, exist_ok=True)
        inp = input_text(case["system"], case["mesh"], case["symmetry"], args.backend,
                         args.eps_symmetry)
        (directory / f"{name}.inp").write_text(inp)
        written.append(case)
    print(f"Wrote {len(written)} inputs under {args.output_dir}", flush=True)
    if args.generate_only:
        return

    if not args.binary and not args.reuse_only:
        parser.error("--binary is required unless --generate-only or --reuse-only is given")
    binary = args.binary.resolve() if args.binary else None
    pinned = False
    if not args.skip_version_check and binary is not None:
        version = subprocess.check_output([binary, "--version"], text=True)
        revision = re.search(r"Source code revision\s+([0-9a-f]+)", version)
        if not revision or not COMMIT.startswith(revision[1]):
            raise SystemExit("Binary version does not match the manuscript snapshot "
                             "(use --skip-version-check to override)")
        pinned = True
    check_energies = args.check_energies or pinned
    if args.datadir:
        datadir = args.datadir.resolve()
    elif args.source:
        datadir = args.source.resolve() / "data"
    else:
        datadir = Path(os.environ.get("CP2K_DATA_DIR", ""))
    env = os.environ | {"OMP_NUM_THREADS": str(args.threads), "OPENBLAS_NUM_THREADS": "1"}
    if datadir:
        env["CP2K_DATA_DIR"] = str(datadir)

    results_path = ROOT / "results_additional.json"
    # Merge into any existing results so that partial reruns (e.g. --systems Al_fcc)
    # do not discard the other cases.
    existing = json.loads(results_path.read_text()) if results_path.exists() else []
    results = [r for r in existing if r["case"] not in
               {case_name(c["system"], c["mesh"], c["symmetry"]) for c in cases}]
    failures = []

    def persist():
        merged = sorted(results, key=lambda r: r["case"])
        results_path.write_text(json.dumps(merged, indent=2) + "\n")

    for case in cases:
        system, mesh, symmetry = case["system"], case["mesh"], case["symmetry"]
        name = case_name(system, mesh, symmetry)
        directory = args.output_dir / name
        output = directory / f"{name}.out"
        inp_file = directory / f"{name}.inp"
        if args.reuse_only:
            if not output.exists():
                failures.append(f"{name}: no existing output for --reuse-only")
                continue
            returncode = None
        elif not args.rerun and output.exists() and "PROGRAM ENDED AT" in output.read_text():
            print(f"Reuse {name}", flush=True)
            returncode = 0
        else:
            output.unlink(missing_ok=True)
            with (directory / "launcher.log").open("w") as log:
                process = subprocess.run([binary, "-i", inp_file.name, "-o", output.name],
                                         cwd=directory, env=env, stdout=log,
                                         stderr=subprocess.STDOUT, timeout=36000)
            returncode = process.returncode
            for restart in directory.glob("*.kp*"):
                restart.unlink()
        parsed = parse_output(output.read_text())
        # Magnetic-split KINDs (Co_a/Co_b, Fe_a/Fe_b) intentionally lower the
        # symmetry, so compare against the kind-resolved spglib count there.
        expected = system.get("expected_ibz_kind_resolved", system["expected_ibz"])[mesh["key"]]
        result = {"case": name, "label": system["label"], "mesh": mesh["name"],
                  "symmetry": symmetry, "expected_nk": expected,
                  "expected_nk_ideal": system["expected_ibz"][mesh["key"]],
                  "returncode": returncode,
                  "checked_reference": symmetry and mesh["key"] == "4x4x4_shifted"
                                       and system["reference_4x4x4_shifted"] is not None
                                       and system["reference_4x4x4_shifted"]["status"]
                                           .startswith("converged")} | parsed
        if symmetry and parsed["nk"] != expected:
            failures.append(f"{name}: IBZ count {parsed['nk']} != expected {expected}")
        if returncode and parsed["nk"] != expected:
            failures.append(f"{name}: CP2K exited with {returncode} and no valid k-point list")
        if returncode and args.strict_scf:
            failures.append(f"{name}: CP2K exited with {returncode}")
        if result["checked_reference"]:
            ref = system["reference_4x4x4_shifted"]["energy_hartree"]
            result["reference_energy_hartree"] = ref
            result["energy_delta_hartree"] = None if parsed["energy_hartree"] is None else \
                parsed["energy_hartree"] - ref
            if check_energies and parsed["converged"] and (
                    parsed["energy_hartree"] is None
                    or abs(parsed["energy_hartree"] - ref) > args.ref_tol):
                failures.append(f"{name}: energy {parsed['energy_hartree']} vs reference {ref} "
                                f"exceeds {args.ref_tol:g} Ha")
        results.append(result)
        persist()
        print(json.dumps(result), flush=True)

    if args.full:
        index = {(r["label"], r["mesh"]): r for r in results if not r["symmetry"]}
        for result in results:
            if not result["symmetry"]:
                continue
            full = index.get((result["label"], result["mesh"]))
            if full and full["energy_hartree"] is not None and result["energy_hartree"] is not None:
                delta = abs(full["energy_hartree"] - result["energy_hartree"])
                result["full_grid_delta_hartree"] = delta
                if delta > args.eq_tol:
                    failures.append(f"{result['case']}: reduced vs full energy differ by "
                                    f"{delta:g} Ha (> {args.eq_tol:g})")

    persist()
    if failures:
        print("\nFAILURES:", flush=True)
        for failure in failures:
            print(f"  {failure}", flush=True)
        raise SystemExit(1)
    print(f"\nAll {len(results)} additional cases passed.", flush=True)


if __name__ == "__main__":
    main()
