#!/usr/bin/env python3
"""Reproduce the manuscript's symmetry-reduction comparison for the new systems.

The published `validation_tables.tex` (table `tab:symmetry-validation`) compares,
at a single mesh, five k-point treatments against the direct full grid:

    Full            SYMMETRY F, FULL_GRID T, LATTICE_FFT OFF
    Time reversal   SYMMETRY F, FULL_GRID F, LATTICE_FFT OFF
    K290            SYMMETRY T, FULL_GRID F, SYMMETRY_BACKEND K290
    SPGLIB          SYMMETRY T, FULL_GRID F, SYMMETRY_BACKEND SPGLIB
    Full, FFT       SYMMETRY F, FULL_GRID T, LATTICE_FFT ON

For each of the 12 structures in `structures.json` and each mode it reports the
solved k-point count and the absolute energy, maximum force-component and
maximum stress-component differences relative to the Full run of the same mesh.

Usage
-----
    python3 run_symmetry_modes.py --generate-only
    python3 run_symmetry_modes.py --binary /path/to/cp2k.ssmp --source /path/to/cp2k
    python3 run_symmetry_modes.py --reuse-only
    python3 run_symmetry_modes.py --summarize-only
"""
import argparse
import json
import os
from pathlib import Path
import re
import subprocess
import time

from run_additional import (COMMIT, ROOT, kind_block, scf_block, parse_output)

MESH_SHIFTED = {"name": "4x4x4-shifted", "scheme": "MACDONALD 4 4 4 0.5 0.5 0.5",
                "gamma_centered": False, "key": "4x4x4_shifted"}
MESH_GAMMA = {"name": "4x4x4-gamma", "scheme": "MONKHORST-PACK 4 4 4",
              "gamma_centered": True, "key": "4x4x4_gamma"}
MESH = MESH_SHIFTED

MODES = [
    {"name": "Full", "symmetry": False, "full_grid": True, "lattice_fft": "OFF", "backend": None},
    {"name": "Time reversal", "symmetry": False, "full_grid": False, "lattice_fft": "OFF", "backend": None},
    {"name": "K290", "symmetry": True, "full_grid": False, "lattice_fft": "OFF", "backend": "K290"},
    {"name": "SPGLIB", "symmetry": True, "full_grid": False, "lattice_fft": "OFF", "backend": "SPGLIB"},
    {"name": "Full, FFT requested", "symmetry": False, "full_grid": True, "lattice_fft": "ON", "backend": None},
]


def mode_slug(mode):
    return mode["name"].lower().replace(", ", "-").replace(" ", "-")


def kpoints_block(mode, eps_symmetry, mesh=None):
    mesh = mesh or MESH
    lines = ["    &KPOINTS", f"      SCHEME {mesh['scheme']}", "      WAVEFUNCTIONS COMPLEX",
             "      PARALLEL_GROUP_SIZE 0",
             f"      SYMMETRY {'T' if mode['symmetry'] else 'F'}",
             f"      FULL_GRID {'T' if mode['full_grid'] else 'F'}",
             f"      LATTICE_FFT {mode['lattice_fft']}"]
    if mode["symmetry"]:
        lines.append(f"      EPS_SYMMETRY {eps_symmetry:.1E}")
    if mode["backend"]:
        lines.append(f"      SYMMETRY_BACKEND {mode['backend']}")
    if mesh.get("gamma_centered"):
        lines.append("      GAMMA_CENTERED .TRUE.")
    lines.append("    &END KPOINTS")
    return "\n".join(lines)


def input_text(system, mode, eps_symmetry=1.0e-5, mesh=None):
    mesh = mesh or MESH
    lat = system["lattice"]
    cell = (f"      ABC  {lat['a']:.10f}  {lat['b']:.10f}  {lat['c']:.10f}\n"
            f"      ALPHA_BETA_GAMMA  {lat['alpha']:.6f}  {lat['beta']:.6f}  {lat['gamma']:.6f}")
    coords = "\n".join(f"      {n}  {x:.10f}  {y:.10f}  {z:.10f}"
                       for n, x, y, z in system["coords"])
    kinds = "\n".join(kind_block(k) for k in system["kinds"])
    return f"""! CP2K symmetry-reduction comparison — generated by run_symmetry_modes.py
! Structure:   {system['note']}
! Mode:        {mode['name']}
! Mesh:        {mesh['name']}
!
&GLOBAL
  PROJECT {system['label']}
  RUN_TYPE ENERGY_FORCE
  PRINT_LEVEL MEDIUM
&END GLOBAL

&FORCE_EVAL
  METHOD QS
  STRESS_TENSOR ANALYTICAL
  &DFT
    LSD .TRUE.
    BASIS_SET_FILE_NAME  BASIS_MOLOPT
    POTENTIAL_FILE_NAME  GTH_POTENTIALS
    &MGRID
      CUTOFF 600
      REL_CUTOFF 60
    &END MGRID
    &QS
      EPS_DEFAULT 1.0E-12
    &END QS
{scf_block(system['scf'])}
    &PRINT
      &KPOINTS ON
        FILENAME __STD_OUT__
      &END KPOINTS
    &END PRINT
    &XC
      &XC_FUNCTIONAL PBE
      &END XC_FUNCTIONAL
    &END XC
{kpoints_block(mode, eps_symmetry, mesh)}
  &END DFT
  &SUBSYS
    &CELL
{cell}
      PERIODIC XYZ
    &END CELL
    &COORD
      SCALED .TRUE.
{coords}
    &END COORD
{kinds}
  &END SUBSYS
  &PRINT
    &FORCES ON
    &END FORCES
    &STRESS_TENSOR ON
    &END STRESS_TENSOR
  &END PRINT
&END FORCE_EVAL
"""


def parse_full(text):
    result = parse_output(text)
    forces = re.findall(r"^\s*FORCES\|\s+\d+\s+([-+0-9.Ee]+)\s+([-+0-9.Ee]+)\s+([-+0-9.Ee]+)",
                        text, re.M)
    if not forces:
        blocks = re.findall(r"ATOMIC FORCES in \[a.u.\](.*?)SUM OF ATOMIC FORCES", text, re.S)
        if blocks:
            forces = re.findall(r"^\s*\d+\s+\d+\s+\w+\s+([-+0-9.Ee]+)\s+([-+0-9.Ee]+)\s+([-+0-9.Ee]+)",
                                blocks[-1], re.M)
    result["forces"] = [[float(v) for v in row] for row in forces]
    stress = re.search(r"STRESS\| Analytical stress tensor \[bar\](.*?)STRESS\| 1/3 Trace", text, re.S)
    result["stress"] = [[float(v) for v in row] for row in re.findall(
        r"STRESS\|\s+[xyz]\s+([-+\d.Ee]+)\s+([-+\d.Ee]+)\s+([-+\d.Ee]+)", stress[1])] if stress else []
    return result


def case_name(label, mode):
    return f"{label}-4x4x4-{mode_slug(mode)}"


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--structures", type=Path, default=ROOT / "structures.json")
    parser.add_argument("--output-dir", type=Path,
                        help="default: symmetry_modes/ (shifted) or symmetry_modes_gamma/ (--gamma-centered)")
    parser.add_argument("--gamma-centered", action="store_true",
                        help="use MONKHORST-PACK 4 4 4 instead of the shifted MacDonald grid")
    parser.add_argument("--generate-only", action="store_true")
    parser.add_argument("--reuse-only", action="store_true")
    parser.add_argument("--summarize-only", action="store_true")
    parser.add_argument("--binary", type=Path)
    parser.add_argument("--source", type=Path)
    parser.add_argument("--datadir", type=Path)
    parser.add_argument("--threads", type=int, default=1)
    parser.add_argument("--rerun", action="store_true")
    parser.add_argument("--systems", default="")
    parser.add_argument("--skip-version-check", action="store_true")
    parser.add_argument("--eps-symmetry", type=float, default=1.0E-5)
    parser.add_argument("--eq-tol", type=float, default=1.0E-6)
    args = parser.parse_args()
    if args.threads < 1:
        parser.error("--threads must be positive")

    mesh = MESH_GAMMA if args.gamma_centered else MESH_SHIFTED
    if args.output_dir is None:
        args.output_dir = ROOT / ("symmetry_modes_gamma" if args.gamma_centered
                                  else "symmetry_modes")

    doc = json.loads(args.structures.read_text())
    wanted = {s.strip() for s in args.systems.split(",") if s.strip()}
    systems = [s for s in doc["systems"] if not wanted or s["label"] in wanted]
    args.output_dir.mkdir(parents=True, exist_ok=True)

    if not args.summarize_only:
        written = 0
        for system in systems:
            for mode in MODES:
                name = case_name(system["label"], mode)
                directory = args.output_dir / name
                directory.mkdir(parents=True, exist_ok=True)
                (directory / f"{name}.inp").write_text(
                    input_text(system, mode, args.eps_symmetry, mesh))
                written += 1
        print(f"Wrote {written} inputs under {args.output_dir}", flush=True)
    if args.generate_only:
        return

    if not args.reuse_only and not args.summarize_only:
        if not args.binary:
            parser.error("--binary is required unless --generate-only/--reuse-only is given")
        binary = args.binary.resolve()
        if not args.skip_version_check:
            version = subprocess.check_output([binary, "--version"], text=True)
            revision = re.search(r"Source code revision\s+([0-9a-f]+)", version)
            if not revision or not COMMIT.startswith(revision[1]):
                raise SystemExit("Binary version does not match the manuscript snapshot "
                                 "(use --skip-version-check to override)")
        datadir = (args.datadir.resolve() if args.datadir
                   else args.source.resolve() / "data" if args.source else Path(""))
        env = os.environ | {"OMP_NUM_THREADS": str(args.threads), "OPENBLAS_NUM_THREADS": "1"}
        if datadir:
            env["CP2K_DATA_DIR"] = str(datadir)
        for system in systems:
            for mode in MODES:
                name = case_name(system["label"], mode)
                directory = args.output_dir / name
                output = directory / f"{name}.out"
                if not args.rerun and output.exists() and "PROGRAM ENDED AT" in output.read_text():
                    print(f"Reuse {name}", flush=True)
                    continue
                output.unlink(missing_ok=True)
                started = time.monotonic()
                with (directory / "launcher.log").open("w") as log:
                    process = subprocess.run([binary, "-i", f"{name}.inp", "-o", f"{name}.out"],
                                             cwd=directory, env=env, stdout=log,
                                             stderr=subprocess.STDOUT, timeout=36000)
                for restart in directory.glob("*.kp*"):
                    restart.unlink()
                print(f"Ran {name} in {time.monotonic() - started:.0f}s "
                      f"(rc={process.returncode})", flush=True)
                if process.returncode:
                    raise SystemExit(f"{name}: CP2K exited with {process.returncode}")

    summarize(args.output_dir, systems, args.eq_tol, mesh)


def sci(x):
    if x == 0:
        return "$0$"
    mantissa, exponent = f"{x:.1e}".split("e")
    return f"${mantissa}\\times10^{{{int(exponent)}}}$"


def summarize(output_dir, systems, eq_tol, mesh=None):
    mesh = mesh or MESH_SHIFTED
    suffix = "" if mesh is MESH_SHIFTED else "_gamma"
    rows, results, failures = [], {}, []
    for system in systems:
        modes = {}
        for mode in MODES:
            name = case_name(system["label"], mode)
            output = output_dir / name / f"{name}.out"
            if not output.exists():
                raise SystemExit(f"missing output: {output}")
            modes[mode["name"]] = parse_full(output.read_text())
        ref = modes["Full"]
        if ref["energy_hartree"] is None or ref["nk"] is None:
            failures.append(f"{system['label']}: full-grid run incomplete")
            continue
        for mode in MODES:
            r = modes[mode["name"]]
            de = None if r["energy_hartree"] is None else abs(r["energy_hartree"] - ref["energy_hartree"])
            df = ds = 0.0
            if r["forces"] and ref["forces"]:
                df = max(abs(a - b) for x, y in zip(r["forces"], ref["forces"], strict=True)
                         for a, b in zip(x, y, strict=True))
            if r["stress"] and ref["stress"]:
                ds = max(abs(a - b) for x, y in zip(r["stress"], ref["stress"], strict=True)
                         for a, b in zip(x, y, strict=True))
            rows.append((system["label"], mode["name"], r["nk"], de, df, ds))
            if mode["name"] != "Full" and de is not None and de > eq_tol:
                failures.append(f"{system['label']} {mode['name']}: |dE|={de:g} > {eq_tol:g}")
        results[system["label"]] = modes

    tex = ["\\begin{table}[htbp]",
           "\\centering\\small\\setlength{\\tabcolsep}{4pt}",
           "\\caption{Same-mesh symmetry-reduction comparisons at $4^3$ ("
           + ("Monkhorst-Pack, $\\Gamma$-centred" if mesh is MESH_GAMMA
              else "MacDonald $(1/2,1/2,1/2)$")
           + ") for the additional structures, relative to the direct full-grid "
           "result. Columns report solved k-points and absolute cell-energy, maximum "
           "force-component and maximum stress-component differences. All runs use one OpenMP "
           "thread. The FFT label records the requested option.}",
           "\\label{tab:symmetry-validation-additional" + suffix.replace("_", "-") + "}",
           "\\begin{tabular}{llrrrr}", "\\toprule",
           "System & Mode & $N_k$ & $|\\Delta E|$ ($E_h$) & "
           "$\\|\\Delta F\\|_\\infty$ ($E_h/a_0$) & $\\|\\Delta\\sigma\\|_\\infty$ (bar) \\\\",
           "\\midrule"]
    for label, mode, nk, de, df, ds in rows:
        lbl = label.replace("_", r"\_")
        de_s = "--" if de is None else ("$0$" if de == 0 else sci(de))
        df_s = "$0$" if df == 0 else sci(df)
        ds_s = "$0$" if ds == 0 else sci(ds)
        tex.append(f"{lbl} & {mode} & {int(nk)} & {de_s} & {df_s} & {ds_s} \\\\")
    tex += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    (ROOT / f"symmetry_modes_tables{suffix}.tex").write_text("\n".join(tex))
    (ROOT / f"symmetry_modes_results{suffix}.json").write_text(json.dumps(results, indent=2) + "\n")
    print("\n".join(tex))
    if failures:
        print("WARNINGS:")
        for f in failures:
            print("  " + f)
        raise SystemExit(1)


if __name__ == "__main__":
    main()
